name: Lint, Test, and Generate Coverage report

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with pylint and flake8
        run: |
          pylint --ignore=migrations group
          pylint --ignore=migrations user
          flake8 user, group
      - name: Test with pytest
        run: coverage run -m pytest -v -s
      - name: Generate coverage report
        run: coverage report -m
